version: '3.8'
services:
  devcontainer:
    image: golang-dev:latest
    network_mode: host
    privileged: true
    volumes:
      - ..:/workspaces:cached
      - ../../gopath:/go:cached
    working_dir: /workspaces
    command: sleep infinity
